
import { LayoutProvider } from "~/useContext/layoutContext";
import HeroLanding from "~/components/client/HeroLanding";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body>
      <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  )
}
